site: Index Jekyll Theme

target: https://index.jekyllthemes.io
baseurl: "/thesis"
# host: 172.20.10.4

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "images/small"
    values:
      image: true

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
sass:
  style: compressed

collections:
  evaluation-criteria:
    output: false
  feed:
    output: true
  research-questions:
    output: true
    
## plugins:
#  - jekyll-paginate
#  - jekyll-sitemap

  